# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 08 Nov 2022 06:46:45 +0000
*               @ALL          1
*               @user         8
