<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: nanchao
 * Date: Wed, 09 Nov 2022 20:43:45 +0800
 */

$conf['title'] = '宏';
$conf['start'] = 'welcome';
$conf['lang'] = 'zh';
$conf['tagline'] = '经天地行，宏启世间';
$conf['license'] = 'publicdomain';
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['tocminheads'] = '20';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['proxy']['user'] = 'nanchao';
$conf['proxy']['pass'] = '<b>bGlseTIwMDMwNDIz';
$conf['plugin']['changes']['listmedia'] = 1;
$conf['plugin']['testing']['schnibble'] = 1;
$conf['plugin']['authad']['admin_username'] = 'nanchao';
