# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 08 Nov 2022 06:46:45 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

nanchao:$2y$10$37fNz9kb8eAESyVT0BR6vulZVx1/boihhJwrM650eCHQaLR/XKc5m:南朝:LouisFitzalanHoward@Icloud.com:admin,user
